import type { CollectionConfig } from 'payload'

export const Teachers: CollectionConfig = {
  slug: 'teachers',
  labels: { singular: '老師', plural: '師資陣容' },
  admin: {
    group: '師資',
    useAsTitle: 'name',
    defaultColumns: ['name', 'school', 'featured', 'order'],
  },
  access: { read: () => true },
  fields: [
    { name: 'name', label: '姓名', type: 'text', required: true },
    { name: 'slug', label: 'URL Slug（英文）', type: 'text', required: true, unique: true,
      admin: { description: '例如：wei-yu-shih（用於 /teachers/wei-yu-shih）' } },
    { name: 'title', label: '職稱（內部）', type: 'text',
      admin: { description: '菁英教師 / 金牌老師，不對外顯示' } },
    { name: 'school', label: '就讀/畢業學校', type: 'text', required: true,
      admin: { description: '例：國立台灣大學 資訊工程學系' } },
    {
      name: 'subjects',
      label: '教學科目',
      type: 'select',
      hasMany: true,
      options: [
        { label: '數學', value: '數學' },
        { label: '英文', value: '英文' },
        { label: '物理', value: '物理' },
        { label: '化學', value: '化學' },
        { label: '生物', value: '生物' },
        { label: '國文', value: '國文' },
        { label: '地理', value: '地理' },
        { label: '歷史', value: '歷史' },
        { label: '公民', value: '公民' },
        { label: '自然', value: '自然' },
        { label: '社會', value: '社會' },
      ],
    },
    {
      name: 'levels',
      label: '適合年級',
      type: 'select',
      hasMany: true,
      options: [
        { label: '國中', value: '國中' },
        { label: '高中', value: '高中' },
      ],
    },
    {
      name: 'bio',
      label: '老師介紹',
      type: 'richText',
      admin: { description: '詳細自我介紹，顯示在個人頁面' },
    },
    {
      name: 'experience',
      label: '教學年資描述',
      type: 'text',
      admin: { description: '例：3 年教學經驗，輔導 20+ 學生' },
    },
    {
      name: 'featuredStat',
      label: '亮眼成果（一句話）',
      type: 'text',
      admin: { description: '例：學生平均進步 28 分' },
    },
    { name: 'photo', label: '老師照片', type: 'upload', relationTo: 'media' },
    {
      name: 'introVideo',
      label: '自我介紹影片 URL（YouTube embed）',
      type: 'text',
      admin: { description: '選填。貼上 YouTube 影片 ID 或完整 embed URL' },
    },
    { name: 'rating', label: '評分（1–5）', type: 'number', min: 1, max: 5,
      defaultValue: 5, admin: { description: '後台手動填，一位小數' } },
    { name: 'reviewCount', label: '評論數', type: 'number', defaultValue: 0 },
    { name: 'featured', label: '首頁顯示', type: 'checkbox', defaultValue: false,
      admin: { description: '勾選後會出現在首頁師資區塊（最多顯示 3 位）' } },
    { name: 'order', label: '排序（數字越小越前面）', type: 'number', defaultValue: 99 },
  ],
}
